"""
pg_arrows_tuning.py — every tuning constant the arrow solver reads,
plus the two module-scoped flags that survive across recursive solve
passes.

Two forms of the constants exist:

    _RA_BASE    a frozen object holding the base values
    <NAME>      a destructured let-binding every function reads

_raSetZoom(k) rescales every let-binding by k.  It exists because an
earlier revision coupled the solver tolerances to the wall-view zoom
level; that coupling has since been removed — both views now handle
viewport changes by transforming the cached routes in place, so the
solver tolerances must not vary with either.  _raSetZoom is called
exactly once per solve with k = 1, and every binding therefore holds
its base value.  The function is retained because the call site is a
load-bearing reminder of that decision.
"""


TUNING_JS = r"""
/* ==========================================================================
   SECTION 1 — TUNING CONSTANTS
   ========================================================================== */

const ROUTE_PARALLEL_TOL          = Math.PI / 10;
const ROUTE_PARALLEL_W            = 30.0;
const ROUTE_MILD_W                = 3.0;
const ROUTE_CROSS_W               = 12.0;
const ROUTE_TIP_W                 = 30.0;

const SOLVER_MAX_ITERATIONS       = 60;
const SOLVER_CLUSTER_EARLY_ITER   = 12;
const SOLVER_GROUP_MAX_ROUTES     = 4;
const SOLVER_BUNDLE_MAX_ROUTES    = 8;
const ROUTE_PLACE_PASSES          = 12;
const ROUTE_GROUP_MAX_K           = 6;

const ROUTE_ATTACK_BUNDLE_TOL     = Math.PI / 6;
const ROUTE_CLUSTER_MIN_SIZE      = 3;
const ROUTE_CLUSTER_LONG_MULT     = 2.2;

const ROUTE_REROUTE_MAX_CONFLICTS = 3;
const ROUTE_REROUTE_GRID_STEPS    = 8;
const ROUTE_REROUTE_REFINE_STEPS  = 3;
const ROUTE_REROUTE_MAX_PER_SWEEP = 4;
const REROUTE_LENGTH_W            = 0.3;

const ROUTE_ESCAPE_ANGLE_TOL      = Math.PI / 6;
const ROUTE_ESCAPE_MAX_PASSES     = 2;
const ROUTE_ESCAPE_FROZEN_TAIL    = 2;

const LONG_ATTACK_THRESHOLD       = 200.0;
const SAME_COL_TOL                = 4.0;
const LONG_ATTACK_SPLIT_THRESHOLD = 200.0;

const RA_SOLVE_SIGNATURE_PRECISION = 0.05;
const RA_SOLVE_DEBOUNCE_MS         = 120;
const RA_FLOOR_SCALE_STEPS         = 10;

const _RA_BASE = Object.freeze({
  ROUTE_MIN_SEP:              12.0,
  ROUTE_MIN_OVERLAP:          10.0,
  ROUTE_ACCEPT_SCORE:         10.0,
  ROUTE_TIP_CLEARANCE:        15.0,
  ROUTE_TIP_QUAD_W:           20.0,

  SOLVER_ACCEPTABLE_SCORE:       40.0,
  SOLVER_PARALLEL_BUDGET:        20.0,
  SOLVER_BUNDLE_SPACING_BUDGET:   5.0,
  SOLVER_CROSSING_BUDGET:        12.0,
  SOLVER_ATTACK_PARALLEL_BUDGET:  8.0,
  SOLVER_CLUSTER_BUDGET:         20.0,
  SOLVER_TIP_BUDGET:             20.0,
  SOLVER_MERGE_THRESHOLD:        22,

  SOLVER_MAX_BUNDLE_SPACING:     96,
  SOLVER_MAX_GROUP_SPACING:      72,
  SOLVER_BUNDLE_SPACING_STEP:     6,
  SOLVER_GROUP_SPACING_STEP:      4,
  ROUTE_BUNDLE_SPACING_MIN:      28,
  ROUTE_BUNDLE_TOP_MARGIN:       44,
  ROUTE_BUNDLE_SCREEN_MIN:       50,
  ROUTE_GROUP_SPACING_MIN:       20,
  ROUTE_GROUP_STEP:              14,
  ROUTE_BUNDLE_GAP_LIMIT:        80,

  ROUTE_LAST_SEG_MIN:            22.0,
  ROUTE_PEEL_STAGGER_MIN:         4.0,
  ROUTE_PEEL_STAGGER_MAX:        28.0,
  ROUTE_PEEL_STAGGER_STEP:        4.0,
  BUNDLE_FAN_STEP:               24.0,
  BUNDLE_PERP_FAN_STEP:          20.0,
  BUNDLED_ATTACK_MIN:            22.0,
  BUNDLE_TINY_ATTACK_MAX:        40.0,
  BUNDLE_TINY_PROX:              14.0,
  BUNDLE_JOG_STEP:               20.0,

  ROUTE_CLUSTER_RADIUS:          90.0,
  ROUTE_CLUSTER_GAP:             36.0,
  ROUTE_CLUSTER_LONG_W:          12.0,
  CLUSTER_DROP_STEP:             15.0,
  CLUSTER_CORRIDOR_STAGGER:       5.0,

  ROUTE_REROUTE_MAX_TOTAL:      180.0,
  ROUTE_REROUTE_SPAN:            80.0,
  ROUTE_REROUTE_ACCEPT:          30.0,
  REROUTE_BEND_W:               100.0,

  ROUTE_ESCAPE_PROX:             10.0,
  ROUTE_ESCAPE_MIN_OVERLAP:      30.0,
});

let {
  ROUTE_MIN_SEP,
  ROUTE_MIN_OVERLAP,
  ROUTE_ACCEPT_SCORE,
  ROUTE_TIP_CLEARANCE,
  ROUTE_TIP_QUAD_W,
  SOLVER_ACCEPTABLE_SCORE,
  SOLVER_PARALLEL_BUDGET,
  SOLVER_BUNDLE_SPACING_BUDGET,
  SOLVER_CROSSING_BUDGET,
  SOLVER_ATTACK_PARALLEL_BUDGET,
  SOLVER_CLUSTER_BUDGET,
  SOLVER_TIP_BUDGET,
  SOLVER_MERGE_THRESHOLD,
  SOLVER_MAX_BUNDLE_SPACING,
  SOLVER_MAX_GROUP_SPACING,
  SOLVER_BUNDLE_SPACING_STEP,
  SOLVER_GROUP_SPACING_STEP,
  ROUTE_BUNDLE_SPACING_MIN,
  ROUTE_BUNDLE_TOP_MARGIN,
  ROUTE_BUNDLE_SCREEN_MIN,
  ROUTE_GROUP_SPACING_MIN,
  ROUTE_GROUP_STEP,
  ROUTE_BUNDLE_GAP_LIMIT,
  ROUTE_LAST_SEG_MIN,
  ROUTE_PEEL_STAGGER_MIN,
  ROUTE_PEEL_STAGGER_MAX,
  ROUTE_PEEL_STAGGER_STEP,
  BUNDLE_FAN_STEP,
  BUNDLE_PERP_FAN_STEP,
  BUNDLED_ATTACK_MIN,
  BUNDLE_TINY_ATTACK_MAX,
  BUNDLE_TINY_PROX,
  BUNDLE_JOG_STEP,
  ROUTE_CLUSTER_RADIUS,
  ROUTE_CLUSTER_GAP,
  ROUTE_CLUSTER_LONG_W,
  CLUSTER_DROP_STEP,
  CLUSTER_CORRIDOR_STAGGER,
  ROUTE_REROUTE_MAX_TOTAL,
  ROUTE_REROUTE_SPAN,
  ROUTE_REROUTE_ACCEPT,
  REROUTE_BEND_W,
  ROUTE_ESCAPE_PROX,
  ROUTE_ESCAPE_MIN_OVERLAP,
} = _RA_BASE;

function _raSetZoom(k) {
  if (!isFinite(k) || k <= 0) k = 1;

  ROUTE_MIN_SEP              = _RA_BASE.ROUTE_MIN_SEP              * k;
  ROUTE_MIN_OVERLAP          = _RA_BASE.ROUTE_MIN_OVERLAP          * k;
  ROUTE_ACCEPT_SCORE         = _RA_BASE.ROUTE_ACCEPT_SCORE         * k;
  ROUTE_TIP_CLEARANCE        = _RA_BASE.ROUTE_TIP_CLEARANCE        * k;
  ROUTE_TIP_QUAD_W           = _RA_BASE.ROUTE_TIP_QUAD_W           / k;

  SOLVER_ACCEPTABLE_SCORE    = _RA_BASE.SOLVER_ACCEPTABLE_SCORE    * k;
  SOLVER_PARALLEL_BUDGET     = _RA_BASE.SOLVER_PARALLEL_BUDGET     * k;
  SOLVER_BUNDLE_SPACING_BUDGET =
    _RA_BASE.SOLVER_BUNDLE_SPACING_BUDGET * k;
  SOLVER_CROSSING_BUDGET     = _RA_BASE.SOLVER_CROSSING_BUDGET     * k;
  SOLVER_ATTACK_PARALLEL_BUDGET =
    _RA_BASE.SOLVER_ATTACK_PARALLEL_BUDGET * k;
  SOLVER_CLUSTER_BUDGET      = _RA_BASE.SOLVER_CLUSTER_BUDGET      * k;
  SOLVER_TIP_BUDGET          = _RA_BASE.SOLVER_TIP_BUDGET          * k;
  SOLVER_MERGE_THRESHOLD     = _RA_BASE.SOLVER_MERGE_THRESHOLD     * k;

  SOLVER_MAX_BUNDLE_SPACING  = _RA_BASE.SOLVER_MAX_BUNDLE_SPACING  * k;
  SOLVER_MAX_GROUP_SPACING   = _RA_BASE.SOLVER_MAX_GROUP_SPACING   * k;
  SOLVER_BUNDLE_SPACING_STEP = _RA_BASE.SOLVER_BUNDLE_SPACING_STEP * k;
  SOLVER_GROUP_SPACING_STEP  = _RA_BASE.SOLVER_GROUP_SPACING_STEP  * k;
  ROUTE_BUNDLE_SPACING_MIN   = _RA_BASE.ROUTE_BUNDLE_SPACING_MIN   * k;
  ROUTE_BUNDLE_TOP_MARGIN    = _RA_BASE.ROUTE_BUNDLE_TOP_MARGIN    * k;
  ROUTE_BUNDLE_SCREEN_MIN    = _RA_BASE.ROUTE_BUNDLE_SCREEN_MIN    * k;
  ROUTE_GROUP_SPACING_MIN    = _RA_BASE.ROUTE_GROUP_SPACING_MIN    * k;
  ROUTE_GROUP_STEP           = _RA_BASE.ROUTE_GROUP_STEP           * k;
  ROUTE_BUNDLE_GAP_LIMIT     = _RA_BASE.ROUTE_BUNDLE_GAP_LIMIT     * k;

  ROUTE_LAST_SEG_MIN         = _RA_BASE.ROUTE_LAST_SEG_MIN         * k;
  ROUTE_PEEL_STAGGER_MIN     = _RA_BASE.ROUTE_PEEL_STAGGER_MIN     * k;
  ROUTE_PEEL_STAGGER_MAX     = _RA_BASE.ROUTE_PEEL_STAGGER_MAX     * k;
  ROUTE_PEEL_STAGGER_STEP    = _RA_BASE.ROUTE_PEEL_STAGGER_STEP    * k;
  BUNDLE_FAN_STEP            = _RA_BASE.BUNDLE_FAN_STEP            * k;
  BUNDLE_PERP_FAN_STEP       = _RA_BASE.BUNDLE_PERP_FAN_STEP       * k;
  BUNDLED_ATTACK_MIN         = _RA_BASE.BUNDLED_ATTACK_MIN         * k;
  BUNDLE_TINY_ATTACK_MAX     = _RA_BASE.BUNDLE_TINY_ATTACK_MAX     * k;
  BUNDLE_TINY_PROX           = _RA_BASE.BUNDLE_TINY_PROX           * k;
  BUNDLE_JOG_STEP            = _RA_BASE.BUNDLE_JOG_STEP            * k;

  ROUTE_CLUSTER_RADIUS       = _RA_BASE.ROUTE_CLUSTER_RADIUS       * k;
  ROUTE_CLUSTER_GAP          = _RA_BASE.ROUTE_CLUSTER_GAP          * k;
  ROUTE_CLUSTER_LONG_W       = _RA_BASE.ROUTE_CLUSTER_LONG_W       * k;
  CLUSTER_DROP_STEP          = _RA_BASE.CLUSTER_DROP_STEP          * k;
  CLUSTER_CORRIDOR_STAGGER   = _RA_BASE.CLUSTER_CORRIDOR_STAGGER   * k;

  ROUTE_REROUTE_MAX_TOTAL    = _RA_BASE.ROUTE_REROUTE_MAX_TOTAL    * k;
  ROUTE_REROUTE_SPAN         = _RA_BASE.ROUTE_REROUTE_SPAN         * k;
  ROUTE_REROUTE_ACCEPT       = _RA_BASE.ROUTE_REROUTE_ACCEPT       * k;
  REROUTE_BEND_W             = _RA_BASE.REROUTE_BEND_W             * k;

  ROUTE_ESCAPE_PROX          = _RA_BASE.ROUTE_ESCAPE_PROX          * k;
  ROUTE_ESCAPE_MIN_OVERLAP   = _RA_BASE.ROUTE_ESCAPE_MIN_OVERLAP   * k;
}

let _raFrozenPolylines = null;
let _raEscapeInProgress = false;
"""
